### PR TITLE
v0.3.3

### PR DESCRIPTION
**Pull request by izakp**
Fixes:
- Installing Hokusai via pip with system Python sometimes fails.  Add note to use `--ignore-installed` option if this is the case
- Add `hokusai dev build` subcommand
- Refactoring verbosity, error handling w/ stacktraces printed in verbose mode
- Fix bug whereby docker-compose does not create the default network the first time `hokusai dev` is called
- Version bump to v0.3.3

### CODE REVIEW

**Comment by ashkan18** [comment]
awesome! should we wait for that `hokusai diff` update to add it to same update? I can work on it today or tomorrow

**Comment by izakp** [comment]
@ashkan18 merge plz as it is blocking some other folks who have tried to get Hokusai up and running. But yes lets get the diff updates out next!

**Comment by ashkan18** [comment]
Sure! awesome!

**Comment by orta** [comment]
I've updated the spell checker based on this PR too, with some more docker-y words: https://github.com/artsy/artsy-danger/commit/20f7fbf2a261adf4219f87a2474d38a2b85539f6

**Pull request merged**
