### PR TITLE
Version 0.4.5

### PR DESCRIPTION
**Pull request by izakp**
Notable changes:
- PyInstaller OSX build
- Push git tags to remote on deploy / promote for CI workflow
- Remove history command as it fell out of sync with multiple deployment and printed misleading information (will readdress when implementing deployment manifests in https://github.com/artsy/hokusai/issues/61)
- `registry images` command no longer prints noisy image digest

Changelog for v0.4.5:

* 1a9822a resolve this directory in hokusai.spec
* 5746219 (origin/fea-push-git-tags, fea-push-git-tags) push tags to specified git remote if provided on deploy and promote
* b6406df remove image digest from registry images output
* 2561c03 remove history command
* 3c43592 check project repo exists before updating deployment or running a command
* 5738ff4 bugfix in hokusai/services/deployment.py
* 93219ea include Pyinstaller spec
* 10a7e12 updates to pyinstaller build steps
* ec590d7 updates to distribute with PyInstaller
* 8011f78 read VERSION from module
* 96f8f52 fix Yarn failure in CI build

### CODE REVIEW

**Comment by joeyAghion** [comment]
> * registry images command no longer prints noisy image digest

Might this interfere with releasecop's [somewhat gross] grepping through `registry images` output for git SHAs?

https://github.com/joeyAghion/releasecop/blob/9aebc6f2cdbf1b6062ac522ee1109d33e293f058/lib/releasecop/manifest_item.rb#L31

**Comment by izakp** [comment]
@joeyAghion no the git `SHA1`s are still there of course!  The second column was a digest of the image from ECR which was of little use

**Comment by izakp** [comment]
Ah yes - releasecop should be updated to parse only 2 columns in `hokusai registry images` output

**Comment by izakp** [comment]
@joeyAghion I pinned the hokusai version to 0.4.4 for https://joe.artsy.net/job/releasecop/ - can update it when ready

**Pull request merged**
