### PR TITLE
Deployment timeout options, registry images output options, addition logs options and prettier printing

### PR DESCRIPTION
**Pull request by izakp**
* 987a77d (HEAD -> master) add --label option to logs to filter by additional label selectors
* a10105f print newline only after verbose log line
* 1cdb7b9 add the --previous option to logs commands
* 395d57d use a unique tmp dir to download and configure kubectl
* 36316e7 refactor printing always via smart_str and add some spacing
* 538f5d5 add --timeout flag to deploy and promote and patch deployments with `progressDeadlineSeconds` when rolling out
* 8cf1ce4 add flags --reverse-sort, --limit and --filter-tags to hokusai registry images

This PR adds a default timeout of `600` seconds to all deployment rollouts by patching `deployment.spec.progressDeadlineSeconds` when rolling out new deployments.  It can be overridden by the `--timeout` flag on `hokusai [staging|production|review_app] deploy` and `hokusai pipeline promote` commands.  This will prevent deployments from blocking indefinitely if new replicas fail to start or become ready.

Also includes a few extra options for the `hokusai registry images` command... `--reverse-sort` displays images oldest to newest, `--limit` truncates the output of images (default 20) and `--filter-tags` selects only images matching the provided string (so for instance you can use `--filter-tags staging` to select all `staging` `staging-{deployment_timestamp}` tags or even `--filter-tags 2019` to match on tags created this year.  It also colorizes "production" images green and "staging" images yellow for better readability.

Also also includes a few extra options to `hokusai [staging|production] logs` commands... `--previous` retrieves logs from the previous run of a restarted container, so if you see any Pod restarts, get logs right before the container's crash with the `--previous` flag.  You can also pass additional [label selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) to the logs command with the `--label` option ( in the form of `key=value,key=value`) to further filter the Pods from which you are getting logs... so in the case of Gravity, one use the option `--label component=sidekiq` to get only sidekiq pod's logs.

Finally includes a refactor of `print()` statements lying around to use `common.print_smart` which passes through `common.smart_str` and adds some spacing to output.

### CODE REVIEW

**Comment by dleve123** [comment]
Isac - if I’m understanding correctly, this new release would have a default timeout of 10 mins (600 seconds), correct? I would just confirm that all current Artsy deployments are under that threshold. For example, deploying Prediction isn’t fast (approximately 6-7 mins), so it wouldn’t seem out of the question for other services to take longer.

Alternatively, could these patches be released in a 1.X release? If so, that would signal this valuable, but potentially breaking change.

Out of curiosity, what motivated the additional arguments to the `hokusai registry` commands. Was there feedback that there wasn’t a great developer UX there?

**Comment by izakp** [comment]
@dleve123 

> this new release would have a default timeout of 10 mins (600 seconds), correct? I would just confirm that all current Artsy deployments are under that threshold. For example, deploying Prediction isn’t fast (approximately 6-7 mins), so it wouldn’t seem out of the question for other services to take longer.

Yes this would by default time out deployment rollouts after 10 minutes.  This can be adjusted by setting the `--timeout` option so a `hokusai production deploy $SHA --timeout 900` would have a 15 minute timeout.  Since CircleCI generally times out commands after 10 minutes of no output I thought this was a reasonable default.

I don't think we're ready for a 1.0 release, but we could hold off on this change to a `0.6` release, in which case i'd advise projects to pin to a `5.x` release.  I'm not sure it's a breaking change though.

> Out of curiosity, what motivated the additional arguments to the hokusai registry commands. Was there feedback that there wasn’t a great developer UX there?

@alloy provided some feedback asking for more readable output of this command, as well as the sort and filter options

**Comment by dleve123** [comment]
> Yes this would by default time out deployment rollouts after 10 minutes. This can be adjusted by setting the --timeout option so a hokusai production deploy $SHA --timeout 900 would have a 15 minute timeout. Since CircleCI generally times out commands after 10 minutes of no output I thought this was a reasonable default.

Yeah, so presuming that Circle builds use `hokusai test`, which spin up Docker resources, then this timeout isn't really a new constraint on any system. If so, this makes sense to me, and shouldn't be a breaking change (at least not systematically enough to cause alarm). 👍

**Comment by izakp** [comment]
Added a few more commits around `logs` command advanced options and @joeyAghion https://github.com/artsy/hokusai/commit/395d57ddd14772825393d6b7ac1c21d6e3735925 should address those Jenkins job failures we were seeing when running `hokusai configure` in concurrent jobs when downloading `kubectl` - it was a relatively easy fix

**Comment by izakp** [comment]
@dleve123 happy to revert 538f5d5 for this PR and address that in a subsequent release...  Projects can specify the `deployment.spec.progressDealineSeconds` field if they want to be automatically rolled back - this `--timeout` option just means Hokusai takes care of setting that field.

**Comment by izakp** [comment]
Going to merge this and prepare a pre-release for beta testing!

**Comment by dleve123** [comment]
> That said... I'd prefer to release this and start enforcing a timeout on deployment rollouts across all our apps with no config change (only upgrading to a new Hokusai release) - if any rollout takes more than 10 minutes I'd consider it an issue we should try and address, and I'd prefer that deployments are automatically rolled back rather than stalling - i.e. sitting in a half-deployed state, possibly running 2 versions of code, until we take manual intervention.

Agreed!

**Pull request merged**
