### PR TITLE
[PLATFORM-3388] hokusai scrubs invalid characters from pod names

### PR DESCRIPTION
**Pull request by chr-tatu**
## Jira ticket
[PLATFORM-3388](https://artsyproduct.atlassian.net/browse/PLATFORM-3388)

## Description
Fixing hokusai failure when the username is not valid based on the regex: `[a-z0-9]([-a-z0-9]*[a-z0-9])?`

## Related Issues
- #252
- #218

### CODE REVIEW

**Review by dblandin — APPROVED** [review]
Awesome :100:

**Review by ovasdi — APPROVED** [review]
:shipit:

**Comment by chr-tatu** [comment]
Managed to manually test it using gravity on staging. The results were as expected
- `USER=Christian-%TaTu=_12` resulted in `christian-tatu-12`
- `USER=+a9?/Chr-%TTu_#4_12` resulted in `-a9-chr-ttu-4-12`

I removed the part that added "user" in case the user started with the "-", since the validation if for the full pod `name` and not for `uuid`

**Review by mc-jones — APPROVED** [review]

**Comment by mc-jones** [comment]
Awesome stuff!

**Pull request merged**
