### PR TITLE
docs: updated readme

### PR DESCRIPTION
**Pull request by shaq31415926**
- updated the pyenv set up instructions
- updated the virtualenv set up instructions

### CODE REVIEW

**Comment by alexpopa-artsy** [comment]
LGTM!

**Review by alexpopa-artsy — APPROVED** [review]

**Comment by alexpopa-artsy** [comment]
Adding @artsyjian as reviewer, because I've never approved a PR for hokusai before. 
@artsyjian bit of background: the documentation around setting up pyenv locally was lacking and I remember from my own onboarding that I had issues with it. We decided to update this, since, for all new Data Engineers this is a crucial step and they would be encountering the same issues we did.

Is there anything else we need to do/need to be aware of regarding Hokusai PRs? 

Thank you!

**Review by aryartsy — APPROVED** [review]

**Comment by artsyjian** [comment]
@shaq31415926 - thanks for refining the doc!

**Comment by shaq31415926** [comment]
Thanks @artsyjian - was a joint effort by me and @aryartsy

**Comment by artsyjian** [comment]
> @artsyjian bit of background: the documentation around setting up pyenv locally was lacking and I remember from my own onboarding that I had issues with it. We decided to update this, since, for all new Data Engineers this is a crucial step and they would be encountering the same issues we did.

Do you folks install `pyenv` for hokusai, or is `pyenv` a requirement regardless of hokusai? I ask b/c hokusai install is already covered by [setup script](https://github.com/artsy/potential/blob/8f6a83db75d17b686bab9b6dd4d75c5d9c30d16a/scripts/setup#L86) in Potential repo.

**Comment by shaq31415926** [comment]
@artsyjian we were directed to these instructions for setting up hokusai, and had some issues with the instructions so were trying to be helpful.

**Comment by alexpopa-artsy** [comment]
@artsyjian `pyenv` (or any other virual environment manager) is a best practice and a definite requirement for all new python devs. When I was onboarding I first faced the issue while trying to set up hokusai. The issue was not hokusai itself, but getting `pyenv` to point to the correct python version and making the `mkvirtualenv` and `workon` commands work. This PR fixes that. 

Personally, I think using [direnv](https://direnv.net/) across the org would be a better solution, which would also apply to ruby repos (in addition, the `.env` files can be committed and shared), but this is probably a topic for an RFC.

Please let me know if this is unclear!

**Comment by artsyjian** [comment]
> @artsyjian we were directed to these instructions for setting up hokusai from the onboarding docs ([artsy/potential#385](https://github.com/artsy/potential/issues/385)), and had some issues with the instructions so were trying to be helpful.

@shaq31415926 - Understood. It's helpful indeed. I'll go through the new steps on my machine.

**Comment by artsyjian** [comment]
> @artsyjian `pyenv` (or any other virual environment manager) is a best practice and a definite requirement for all new python devs.

@alexpopa-artsy - Got it. Sounds like it would good to cover this requirement in Potential's setup script where we try to capture all the tooling an engineer needs.

> When I was onboarding I first faced the issue while trying to set up hokusai. The issue was not hokusai itself, but getting pyenv to point to the correct python version and making the mkvirtualenv and workon commands work.

Exactly. `pyvenv`, `virtualenv`, `poetry` are all optional for the purpose of installing/running Hokusai. A simple `brew install hokusai` will do. Sorry for the confusion! I shall re-factor the README and make that clear.

**Review by artsyjian — APPROVED** [review]
The updated commands work fine on my machine. Thanks @shaq31415926 , @aryartsy , @alexpopa-artsy

**Comment by alexpopa-artsy** [comment]
@artsyjian The PR is merged! But I noticed one of the tests failing [release_beta_dockerhub](https://app.circleci.com/pipelines/github/artsy/hokusai?branch=master)
which seems to have been introduced in [this PR](https://github.com/artsy/hokusai/commit/7930029b549e6c5923f6a72e31e0d2d1be71ee40)
Seems to be a dependency mismatch. This error is a bit older, so I assume you're already familiar with it, but wanted to flag it just in case!

**Pull request merged**
